---
#- name: restart tor
#  service: name=tor state=restarted

- name: stop-and-disable default tor
  become: yes
  service: name=tor state=stopped enabled=no

- name: restart apparmor
  become: yes
  service: name=apparmor state=restarted

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload

- name: re-gather facts
  setup:
