- name: Check that borg is installed (see borg-common role)
  file: path=/usr/local/bin/borg state=file follow=yes

- name: Create dedicated ssh key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: "{{ borg_ynh_backup_ssh_key }}"
    ssh_key_comment: "borg backup root@{{ ansible_hostname }}"

- name: Setup cron task
  template: src=borg-ynh-backup.j2 dest=/etc/cron.d/borg-ynh-backup mode=0744