---
  - name: flush handlers (in case nginx has to restart first)
    meta: flush_handlers

  - name: add backports repository (for jessie)
    apt_repository:
      repo: 'deb http://http.debian.net/debian jessie-backports main'
      state: present
      update_cache: yes
    when: ansible_lsb.codename ==  "jessie"

  - name: install certbot
    apt:
      pkg: certbot
      update_cache: yes
      cache_valid_time: 1800
      default_release: "{% if ansible_distribution_release == 'jessie'%}jessie-backports{% endif %}"
    when: ansible_lsb.codename == "jessie"

  - name: Ensure webroot exists
    file: path="{{ letsencrypt_webroot_path }}" state=directory recurse=yes mode="a+rw"

  - name: Attempt to get the certificate using the webroot authenticator
    command: "{{ letsencrypt_command }} -a webroot --webroot-path {{ letsencrypt_webroot_path }} certonly -d {{ item }}"
    args:
      creates: "/etc/letsencrypt/live/{{ item }}"
    with_items: "{{ letsencrypt_cert_domains }}"

  - name: Install cron
    apt: name=cron

  - name: Install renewal cron
    cron: name="Let's Encrypt Renewal" day="{{ letsencrypt_renewal_frequency.day }}" hour="{{ letsencrypt_renewal_frequency.hour }}" minute="{{ letsencrypt_renewal_frequency.minute }}" job="certbot renew --renew-hook 'systemctl reload nginx'> /dev/null"
