- name: Add ympd user
  user: name={{ ympd_user }}

- name: Install ympd build dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - cmake
    - libmpdclient-dev
    - openssl
    - libssl-dev

- name: Clone ympd
  git: repo="{{ ympd_git_repo }}" dest="{{ ympd_clone_dir }}"
  register: code

- name: Make build directory
  file:
    path: "{{ ympd_build_dir }}"
    state: directory
  when: code.changed

- name: Bootstrap cmake
  command: cmake ..  -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/
  args:
    chdir: "{{ ympd_build_dir }}"
    creates: "{{ ympd_build_dir }}/ympd"
  when: code.changed

- name: make
  command: make
  args:
    chdir: "{{ ympd_build_dir }}"
    creates: "{{ ympd_build_dir }}/ympd"
  when: code.changed

- name: make install
  command: make install
  args:
    chdir: "{{ ympd_build_dir }}"
  when: code.changed
  notify: Restart ympd

- name: Installs upstart script
  template: src=ympd.conf.upstart.j2 dest="/etc/init/ympd.conf"
  notify: Restart ympd

- name: Enable/start ympd
  service: name=ympd enabled=yes state=started
