- name: Setup rsync backup client
  import_tasks: setup.yml
  when: not rsync_backup_client_disable

- name: Disable rsync backup client
  import_tasks: disable.yml
  when: rsync_backup_client_disable
