- name: Install bind9
  apt: pkg=bind9 state=installed update_cache=yes cache_valid_time=360

- name: Build named.conf.local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local
  notify: Restart bind

- name : Build bind db files
  template:
    src: db.j2
    dest: "/etc/bind/db.{{ item.name }}"
  with_items: bind_master_domains
  notify: Restart bind

- name: Enable and start bind9
  service: name=bind9 enabled=yes state=started
