# This first task is actually required by ijavascript
# to get a recent version of node (jessie-backports contains one, but with no
# npm…)
# Seems un-needed on strecth (but not tested)
- name: Install node from nodesource as ijs wont run with node 0.10x
  import_tasks: nodesource.yml

- name: install apt dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=1800
  with_items:
    #- npm           # Taken care by nodesource step
    #- nodejs-legacy # Taken care by nodesource step
    - virtualenv
    - python3-dev

- name: create dedicated user
  user:
    name: jupyterhub
    groups: shadow  # so that it can authenticate others with PAM
    home: /opt/jupyterhub

- name: ensure jupyterhub-users group exists
  group:
    name: jupyterhub-users
    state: present

- name: install pip dependencies
  pip:
    name: "{{ item }}"
    virtualenv: /opt/jupyterhub/venv
    virtualenv_python: python3
  with_items:
    - jupyterhub
    - sudospawner
  become: jupyterhub
  notify: restart jupyterhub

- name: Install npm deps
  npm:
    name: configurable-http-proxy
    global: yes

- name: Authorize jupyterhub to spawn notebooks for jupyterhub-users members
  copy:
    content: "jupyterhub ALL = (%jupyterhub-users) NOPASSWD: /opt/jupyterhub/venv/bin/sudospawner\n"
    dest: /etc/sudoers.d/50-jupyterhub
    mode: 0440
    validate: visudo -cf %s

# Adding jupyterhub to shadow group would not be the right thing, as it gives
# too much power.
- name: authorize jupyterhub to do PAM auth
  acl:
    path: /etc/shadow
    entry: "user:jupyterhub:r"
    state: present

- name: authorize jupyterhub to log events in lastlog
  acl:
    path: /var/log/lastlog
    entry: "user:jupyterhub:rw"
    state: present

- name: make sure dedicated ro-dirs exist
  file: path={{item}}/ state=directory owner=root mode=0755
  with_items:
    - /etc/jupyterhub
    - /etc/jupyter/templates

- name: make sure dedicated rw-dirs exist
  file: path={{ item }} state=directory owner=jupyterhub mode=0755
  with_items:
    - /var/log/jupyterhub

- name: install custom config file
  template:
    src: jupyterhub_config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
  notify: restart jupyterhub

- name: systemd script is in place
  template:
    src: jupyterhub.service.j2
    dest: /etc/systemd/system/jupyterhub.service
  notify:
    - reload systemd
    - restart jupyterhub

- name: jupyterhub is started
  service: name=jupyterhub state=started

- name: Install ijavascript notebook kernel
  import_tasks: ijavascript.yml
