- name : Install borg via pip
  import_tasks: pip_install.yml
  when: borg_install_method == 'pip'

- name: Install borg via apt
  import_tasks: apt_install.yml
  when: (borg_install_method == 'apt') and (ansible_lsb.codename == 'jessie')
