- name: Puts the network interfaces conf in place
  template: src=interfaces.j2 dest=/etc/network/interfaces
#  notify: restart networking

- name: Install vlan tools
  apt: pkg=vlan state=present

- name: Load vlan module on boot
  copy: src=vlan-module.conf dest=/etc/modules-load.d/vlan.conf
  notify: reload kernel modules

- name: Puts on-interface-up script to restore firewall rules
  copy: src=if-pre-up-iptables dest=/etc/network/if-pre-up.d/iptables mode=744

- name: Set IPv4 firewall rules
  template: src=iptables.j2 dest=/etc/iptables
  notify: reload firewall rules

- name: Set IPv6 firewall rules
  template: src=ip6tables.j2 dest=/etc/ip6tables
  notify: reload firewall rules

# TCP offloading with e1000e module was buggy with errors like
# e1000e 0000:00:19.0 eth0: Detected Hardware Unit Hang
# ...
# e1000e 0000:00:19.0 eth0: Reset adapter unexpectedly
# See http://serverfault.com/questions/616485/
- name: Disable TCP offloading features
  copy:
    src: files/if-up-disable-tcp-offloading
    dest: /etc/network/if-up.d/disable-tcp-offloading
    mode: 0744
