- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades cache_valid_time=3600

- name: Install heirloom-mailx (for notifications)
  apt: pkg=heirloom-mailx cache_valid_time=3600

- name: Set unattended-upgrades conf
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
